# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"5\n\x0fMultiplyRequest\x12\x10\n\x08number_1\x18\x01 \x01(\x05\x12\x10\n\x08number_2\x18\x02 \x01(\x05\"!\n\x0fMultipliedReply\x12\x0e\n\x06result\x18\x01 \x01(\x03\x32S\n\tCalculate\x12\x46\n\x08Multiply\x12\x1b.calculator.MultiplyRequest\x1a\x1b.calculator.MultipliedReply\"\x00\x42\x34\n\x1aio.grpc.example.calculatorB\x0f\x43\x61lculatorProtoP\x01\xa2\x02\x02\x43Lb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032io.grpc.example.calculatorB\017CalculatorProtoP\001\242\002\002CL'
  _MULTIPLYREQUEST._serialized_start=32
  _MULTIPLYREQUEST._serialized_end=85
  _MULTIPLIEDREPLY._serialized_start=87
  _MULTIPLIEDREPLY._serialized_end=120
  _CALCULATE._serialized_start=122
  _CALCULATE._serialized_end=205
# @@protoc_insertion_point(module_scope)
