# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_streaming.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63lient_streaming.proto\"%\n\x0bSendRequest\x12\x16\n\x06queues\x18\x01 \x01(\x0b\x32\x06.Queue\"r\n\x05Queue\x12\x1d\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x0f.Queue.TimeData\x1aJ\n\x08TimeData\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x15\n\rspeaker_score\x18\x02 \x01(\x01\x12\x14\n\x0cspeaker_name\x18\x03 \x01(\t\"\x1f\n\x0cSendResponse\x12\x0f\n\x07message\x18\x01 \x01(\t29\n\x08SendData\x12-\n\nStreamData\x12\x0c.SendRequest\x1a\r.SendResponse\"\x00(\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_streaming_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SENDREQUEST._serialized_start=26
  _SENDREQUEST._serialized_end=63
  _QUEUE._serialized_start=65
  _QUEUE._serialized_end=179
  _QUEUE_TIMEDATA._serialized_start=105
  _QUEUE_TIMEDATA._serialized_end=179
  _SENDRESPONSE._serialized_start=181
  _SENDRESPONSE._serialized_end=212
  _SENDDATA._serialized_start=214
  _SENDDATA._serialized_end=271
# @@protoc_insertion_point(module_scope)
