# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import send_tuples_to_queue_pb2 as send__tuples__to__queue__pb2


class SendDataStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SingleData = channel.unary_unary(
                '/SendData/SingleData',
                request_serializer=send__tuples__to__queue__pb2.SendRequest.SerializeToString,
                response_deserializer=send__tuples__to__queue__pb2.SendResponse.FromString,
                )
        self.SingleDataAgain = channel.unary_unary(
                '/SendData/SingleDataAgain',
                request_serializer=send__tuples__to__queue__pb2.SendRequest.SerializeToString,
                response_deserializer=send__tuples__to__queue__pb2.SendResponse.FromString,
                )


class SendDataServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SingleData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SingleDataAgain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SendDataServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SingleData': grpc.unary_unary_rpc_method_handler(
                    servicer.SingleData,
                    request_deserializer=send__tuples__to__queue__pb2.SendRequest.FromString,
                    response_serializer=send__tuples__to__queue__pb2.SendResponse.SerializeToString,
            ),
            'SingleDataAgain': grpc.unary_unary_rpc_method_handler(
                    servicer.SingleDataAgain,
                    request_deserializer=send__tuples__to__queue__pb2.SendRequest.FromString,
                    response_serializer=send__tuples__to__queue__pb2.SendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'SendData', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SendData(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SingleData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SendData/SingleData',
            send__tuples__to__queue__pb2.SendRequest.SerializeToString,
            send__tuples__to__queue__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SingleDataAgain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/SendData/SingleDataAgain',
            send__tuples__to__queue__pb2.SendRequest.SerializeToString,
            send__tuples__to__queue__pb2.SendResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
