# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bidirectional_with_tuples.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62idirectional_with_tuples.proto\x12\rbidirectional\"\x1e\n\x08\x44\x61taList\x12\x12\n\ntimestamps\x18\x01 \x01(\x01\"9\n\x10\x44\x61taQueueRequest\x12%\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x17.bidirectional.DataList\"\"\n\x0fReceivedMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2f\n\rBidirectional\x12U\n\x0cSendDiarData\x12\x1f.bidirectional.DataQueueRequest\x1a\x1e.bidirectional.ReceivedMessage\"\x00(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bidirectional_with_tuples_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DATALIST._serialized_start=50
  _DATALIST._serialized_end=80
  _DATAQUEUEREQUEST._serialized_start=82
  _DATAQUEUEREQUEST._serialized_end=139
  _RECEIVEDMESSAGE._serialized_start=141
  _RECEIVEDMESSAGE._serialized_end=175
  _BIDIRECTIONAL._serialized_start=177
  _BIDIRECTIONAL._serialized_end=279
# @@protoc_insertion_point(module_scope)
